### PR TITLE
Bug fixes related to query parameters and .jpeg extension

### PR DESCRIPTION
**Pull request by craftycorvid**
Fixed issue importing files with the .jpeg extension
Fixed issue importing files with query parameters in the URL

### CODE REVIEW

**Comment by VR51** [comment]
Before I merge these changes to this branch I need to confirm the removal of three is_external_file() tests will not cause the importer to duplicate already locally stored files. The other 2 changes look fine.

**Comment by craftycorvid** [comment]
Sure thing.
For what it's worth I ran the modified script on a blog that needed ~1000 images imported across ~80 posts with no issues.

The reason for removing all those checks is that they fail on URLs with query parameters. It might be more prudent to modify is_external_file() to extract the path and then check the extensions.

**Comment by VR51** [comment]
Did the blog you ran it on have locally hosted images too?

**Comment by craftycorvid** [comment]
Yes, it did. A few hundred.
And I ran it on posts that had a mix of locally hosted and external images.

**Comment by VR51** [comment]
Thank you, Ivan0xFF.

**Comment by VR51** [comment]
Looking at is_external_file(), the function doesn't do what its name suggests it does. The author of the original plugin might have intended to use external_image_getext() at some point, which appears to be used nowhere by the plugin.

I have a few ideas. A rewrite is in order.

**Comment by VR51** [comment]
I've merged these changes to Master. I have made a few additional changes which will be applied in a few moments too. So.. your commits are present but moved around by a few lines. Thanks for your help, @Ivan0xFF.

**Pull request merged**
